plugin:
    name:        'zaxbux.securityheaders::lang.plugin.name'
    description: 'zaxbux.securityheaders::lang.plugin.description'
    author:      'Zachary Schneider'
    icon:        'icon-shield'
    homepage:    'https://www.zacharyschneider.ca'
